# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.11.2
  hooks:
    # Run the linter.
    - id: ruff
      name: "Linting"
    # Sort imports/remove unused
    - id: ruff
      name: "Sorting imports"
      args: [ --fix, --select, I ]
    - id: ruff
      name: "Removing unused imports"
      args: [ --fix]
    # Run the formatter.
    - id: ruff-format
      name: "Formating code"
