import os
from pathlib import Path
from shutil import which

from loguru import logger

from d2rloader.core.exception import ProcessingError
from d2rloader.models.account import Account
from d2rloader.models.setting import Setting

# The initial version of this script was auto-generated by Lutris
# using "lutris -b ~/start.sh diablo-2-resurrected"
START_SCRIPT = """
#!/bin/bash

# This file is autogenerated. Do not edit!

# Environment variables
export __GL_SHADER_DISK_CACHE="1" # avoid recompiling shaders each time
export __GL_SHADER_DISK_CACHE_PATH="{WINEPREFIX}" # shaders cache path
export STAGING_SHARED_MEMORY="1" # https://gitlab.winehq.org/wine/wine-staging/-/wikis/Configuration/Environment-Variables#Shared_Memory
export DXVK_STATE_CACHE_PATH="{WINEPREFIX}"
export DXVK_LOG_LEVEL="error" # only log errors
export DXVK_NVAPIHACK="0"
export DXVK_ENABLE_NVAPI="1"
export PROTON_DXVK_D3D8="1"
export UMU_LOG="0"  # set to 1 to display logs from umu
export WINEDEBUG="-all" # disable debug messages
export WINE_LARGE_ADDRESS_AWARE="1"
export WINEARCH="win64"
export WINEPREFIX="{WINEPREFIX}"
export WINEESYNC="1" # https://github.com/zfigura/wine/blob/esync/README.esync
export WINEFSYNC="1"
export WINEDLLOVERRIDES="winemenubuilder=" # https://gitlab.winehq.org/wine/wine/-/wikis/Commands/winemenubuilder

# Working Directory
cd '{GAME_PATH}'

# Command

# Use gamemode if available
if ! [ -x "$(command -v gamemoderun)" ]; then
    echo 'gamemode is not installed - starting D2R.exe without gamemoderun' >&2
    {UMU_LAUNCHER} '{GAME_PATH}/D2R.exe' -w -username {USERNAME} -password {PASSWORD} -address {REGION} {PARAMS}
else
    gamemoderun {UMU_LAUNCHER} '{GAME_PATH}/D2R.exe' -w -username {USERNAME} -password {PASSWORD} -address {REGION} {PARAMS}
fi
"""


class UmuManager:
    home: Path = Path.home()

    def __init__(self, settings: Setting, account: Account) -> None:
        self.settings: Setting = settings
        self.account: Account = account

    @property
    def umu_launcher(self):
        umu_path = which("umu-run")
        if umu_path is None:
            logger.error(
                "Couldn't find 'umu-run'! Did you forget to install 'umu-launcher'?'"
            )
            raise ProcessingError("umu-run not found in PATH!")
        return Path(umu_path)

    @property
    def wineprefix_account(self):
        return Account.wineprefix_account(
            self.settings,
            self.account,
        )

    @property
    def start_script_log_path(self):
        return Path(self.wineprefix_account, "umu.log")

    @property
    def start_script_path(self):
        return Path(self.wineprefix_account, "start.sh")

    def render_start_script(self):
        return START_SCRIPT.format(
            WINEPREFIX=self.wineprefix_account,
            GAME_PATH=self.settings.game_path,
            UMU_LAUNCHER=self.umu_launcher,
            USERNAME=self.account.email,
            PASSWORD=self.account.password,
            REGION=self.account.region.value,
            PARAMS=self.account.params,
        )

    def save_start_script(self, force: bool = True):
        if (
            not force
            and self.wineprefix_account.exists()
            and self.start_script_path.exists()
        ):
            logger.warning("Wineprefix already exists!")
            return
        else:
            os.makedirs(self.wineprefix_account, exist_ok=True)

        logger.debug(f"Using game path: '{self.settings.game_path}'")
        logger.debug(f"Writing file '{self.start_script_path}'...")

        with open(self.start_script_path, "w") as f:
            f.write(self.render_start_script())
        return True
