import os
import subprocess
import urllib.request
from pathlib import Path
from shutil import which
from typing import TYPE_CHECKING

from loguru import logger

from d2rloader.constants import CONFIG_BASE_DIR, D2RREG_URL, D2RREG_VERSION
from d2rloader.core.exception import ProcessingError
from d2rloader.models.account import Account, AuthMethod

if TYPE_CHECKING:
    from d2rloader.core.state import D2RLoaderState


# The initial version of this script was auto-generated by Lutris
# using "lutris -b ~/start.sh diablo-2-resurrected"
START_SCRIPT = """
#!/bin/bash

# This file is autogenerated. Do not edit!

# Environment variables
export __GL_SHADER_DISK_CACHE="1" # avoid recompiling shaders each time
export __GL_SHADER_DISK_CACHE_PATH="{WINEPREFIX}" # shaders cache path
export STAGING_SHARED_MEMORY="1" # https://gitlab.winehq.org/wine/wine-staging/-/wikis/Configuration/Environment-Variables#Shared_Memory
export DXVK_STATE_CACHE_PATH="{WINEPREFIX}"
export DXVK_LOG_LEVEL="error" # only log errors
export DXVK_NVAPIHACK="0"
export DXVK_ENABLE_NVAPI="1"
export PROTON_DXVK_D3D8="1"
export UMU_LOG="0"  # set to 1 to display logs from umu
export WINEDEBUG="-all" # disable debug messages
export WINE_LARGE_ADDRESS_AWARE="1"
export WINEARCH="win64"
export WINEPREFIX="{WINEPREFIX}"
export WINEESYNC="1" # https://github.com/zfigura/wine/blob/esync/README.esync
export WINEFSYNC="1"
export WINEDLLOVERRIDES="winemenubuilder=" # https://gitlab.winehq.org/wine/wine/-/wikis/Commands/winemenubuilder

# Working Directory
cd '{GAME_PATH}'

# Command

# Use gamemode if available
if ! [ -x "$(command -v gamemoderun)" ]; then
    echo 'gamemode is not installed - starting D2R.exe without gamemoderun' >&2
    {UMU_LAUNCHER} '{GAME_PATH}/D2R.exe' {PARAMS}
else
    gamemoderun {UMU_LAUNCHER} '{GAME_PATH}/D2R.exe' {PARAMS}
fi
"""


class UmuManager:
    home: Path = Path.home()

    def __init__(self, state: "D2RLoaderState") -> None:
        self._state: D2RLoaderState = state

    @property
    def umu_launcher(self):
        umu_path = which("umu-run")
        if umu_path is None:
            logger.error(
                "Couldn't find 'umu-run'! Did you forget to install 'umu-launcher'?'"
            )
            raise ProcessingError("umu-run not found in PATH!")
        return Path(umu_path)

    def get_wineprefix_account(self, account: Account):
        return Account.wineprefix_account(
            self._state.settings.data,
            account,
        )

    def get_start_script_log_path(self, account: Account):
        return Path(self.get_wineprefix_account(account), "umu.log")

    def get_start_script_path(self, account: Account):
        return Path(self.get_wineprefix_account(account), "start.sh")

    def start(self, account: Account):
        logger.debug("Starting umu-launcher")

        game_settings = self._state.game_settings.get_game_settings(account)

        params: list[str] = []
        if account.auth_method == AuthMethod.Password:
            if (
                len(account.email) == 0
                or account.password is None
                or len(account.password) == 0
            ):
                raise ProcessingError("No email/password provided")

            params.extend(
                [
                    "-username",
                    account.email,
                    "-password",
                    account.password,
                    "-address",
                    account.region.value,
                ]
            )
        elif account.auth_method == AuthMethod.Token:
            self._update_web_token_value(account)

            params.extend(["-uid", "osi", "-address", account.region.value])

        if account.params is not None:
            params.extend(
                [param.strip() for param in account.params.split(" ") if param]
            )

        if self._save_start_script(account, params):
            try:
                with open(self.get_start_script_log_path(account), "w") as logfile:
                    game_settings.set_account_game_settings()
                    logger.info(
                        f"Launching instance: {self.get_start_script_path(account).absolute()}"
                    )
                    logger.debug(
                        f"Using GAME_PATH: {self._state.settings.data.game_path}"
                    )
                    proc = subprocess.Popen(
                        ["sh", self.get_start_script_path(account)], stderr=logfile
                    )
                    return proc.pid
            except Exception as e:
                logger.error(e)
                raise ProcessingError(
                    f"Error occured during executing {self.get_start_script_path(account)}",
                    e,
                )

    def _update_web_token_value(self, account: Account):
        logger.debug(f"Updating WEB_TOKEN value for account: {account.profile_name}")

        if account.token is None:
            raise ProcessingError("No token provided")

        self._check_d2rreg()

        cmd = [
            "umu-run",
            f"{CONFIG_BASE_DIR}/d2rreg.exe",
            "--update-token",
            account.token,
        ]
        logger.debug(f"Update WEB_TOKEN cmd: executing '{' '.join(cmd[0:-1])}'")
        output = subprocess.run(
            cmd,
            capture_output=True,
            env={
                **os.environ,
                "PROTON_VERB": "runinprefix",
                "WINEDEBUG": "-all",
                "WINEPREFIX": f"{self.get_wineprefix_account(account)}",
            },
        )
        logger.trace(f"_update_web_token_value output stderr: {output.stderr}")
        logger.trace(f"_update_web_token_value output stdout: {output.stdout}")
        return output.stdout

    def _check_d2rreg(self):
        if (
            not os.path.exists(os.path.join(CONFIG_BASE_DIR, "d2rreg.exe"))
            or self._state.settings.data.d2rreg_version != D2RREG_VERSION
        ):
            logger.info(f"Updating d2rreg.exe to {D2RREG_VERSION}...")
            self._state.settings.set(d2rreg_version=D2RREG_VERSION)

            req = urllib.request.urlopen(D2RREG_URL).read()
            with open(os.path.join(CONFIG_BASE_DIR, "d2rreg.exe"), "wb") as f:
                f.write(req)
            logger.info(
                f"d2rreg.exe saved to {os.path.join(CONFIG_BASE_DIR, 'd2rreg.exe')}"
            )
        return

    def _render_start_script(self, account: Account, params: list[str]):
        return START_SCRIPT.format(
            WINEPREFIX=self.get_wineprefix_account(account),
            GAME_PATH=self._state.settings.data.game_path,
            UMU_LAUNCHER=self.umu_launcher,
            USERNAME=account.email,
            PASSWORD=account.password,
            REGION=account.region.value,
            PARAMS=" ".join(params),
        )

    def _save_start_script(
        self, account: Account, params: list[str], force: bool = True
    ):
        if (
            not force
            and self.get_wineprefix_account(account).exists()
            and self.get_start_script_path(account).exists()
        ):
            logger.warning("Wineprefix already exists!")
            return
        else:
            os.makedirs(self.get_wineprefix_account(account), exist_ok=True)

        logger.debug(f"Using game path: '{self._state.settings.data.game_path}'")
        logger.debug(f"Writing file '{self.get_start_script_path(account)}'...")

        with open(self.get_start_script_path(account), "w") as f:
            f.write(self._render_start_script(account, params))
        return True
