name: Package Application with Pyinstaller

on:
  push:
    tags:
      - "v*"
      
permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install the latest version of uv and set the python version
      uses: astral-sh/setup-uv@v5
      with:
        python-version: 3.13

    - name: Make PyInstaller Package
      run: uv run pyinstaller D2RLoader.spec --noconfirm

    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.6
      with:
        type: 'zip'
        filename: 'D2RLoader.windows.zip'
        path: 'dist/D2RLoader'

    - name: Add release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "D2RLoader.windows.zip"
        artifactErrorsFailBuild: true
        allowUpdates: true
        generateReleaseNotes: true
        omitBodyDuringUpdate: true
        omitDraftDuringUpdate: true
        replacesArtifacts: true
